home/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from home.views import HomeView, login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    #url(r'^logout/', logout, name='logout'),
    #url(r'^login/$', login, name='login'),
    # url(r'^login_process/$', login_process, name='login_process'),
    # url(r'^login_failed/$', views.login_failed, name='login_failed'),
    # url(r'^logout/$', views.logout, name='logout'),
    # url(r'^recommend/$', views.get_recommendation, name='recommend'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

newgames/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from newgames.views import IndexView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

steamrec/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("home.urls")),
    url(r'^newgames/', include("newgames.urls", namespace='newgames'))
]

templates/home_content.html
{% extends "index.html" %}
{% load staticfiles %}

{% block home_content %}
  <div id="main_content" class="container row">


      <div id="newgames" class="col s12 m12 l6">
        <a href="{% url 'newgames:index' %}">
          <div class="card home-card">
            <div class="card-image">
              <img src="{% static 'img/new_games2.jpg' %}">
              <!-- <span class="card-title">NEW GAMES</span> -->
            </div>
            <div class="card-content">
              <p>You don't know what to buy? Steam recommender system doesn't show you any good games? Then use this service! You don't need to fill any forms, just press one button!</p>
            </div>
            <div class="card-action">
              <h5 class="recommend_button">NEW GAMES</h5>
            </div>
          </div>
        </a>
      </div>
      
      <div id="playnext" class=" col s12 m12 l6">
        <a href="#">
          <div class="card home-card">
            <div class="card-image">
              <img src="{% static 'img/tags.jpg' %}">
              <!-- <span class="card-title">GAMES BY DESCRIPTION</span> -->
            </div>
            <div class="card-content">
              <p>Try this service if you want to find something new, just describe the game you want to play in couple of sentences.</p>
            </div>
            <div class="card-action">
              <h5 class="recommend_button">COMING SOON</h5><!-- GAMES BY DESCRIPTION -->
            </div>
          </div>
        </a>
      </div>

  </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>STEAMREC</title>
  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!--Import materialize.css-->
  <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.css' %}"  media="screen,projection"/>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({
      google_ad_client: "ca-pub-8214456136951730",
      enable_page_level_ads: true
    });
  </script>
</head>

<body>
  <header>
    {% include 'navbar.html' %}
  </header>
  <main>
    {% block home_content %}
    {% endblock %}

    {% block newgames %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 align="left" class="white-text">Help us</h5>
          <p align="left" class="grey-text text-lighten-4">We hoped you have enjoyed using SteamRec! If you feel SteamRec helped you out and want to support the team, send us over a donation!</p>
          <form align="left" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank">
          <input type="hidden" name="cmd" value="_s-xclick">
          <input type="hidden" name="hosted_button_id" value="JPKFHCWKKMRWW">
          <button type="submit" id="donate" name="submit" class="waves-effect waves-light btn">DONATE</button>
<!--           <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"> -->
<!--           <img alt="" border="0" src="https://www.paypalobjects.com/ru_RU/i/scr/pixel.gif" width="1" height="1"> -->
          </form>

        </div>
        <div class="col l4 offset-l2 s12">
          <h5 align="left" class="white-text">Contact Us</h5>
          <ul>
            <li align="left" style="color:#FFFFFF">Konstantin: konstgazha@yandex.ru</li>
            <li align="left" style="color:#FFFFFF">Vlad: <a target="_blank" class="grey-text text-lighten-3" href="http://steamcommunity.com/id/GoodLuther">steam</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="../static/js/materialize.min.js"></script>
</body>

</html>

templates/navbar.html
{% load staticfiles %}


{% block navbar %}
  <!-- Dropdown Structure -->
  <ul id="drpodown-menu" class="dropdown-content">
    <li><a href="{% url 'newgames:index' %}">NEW GAMES</a></li>
    <!-- <li><a href="/">HOW TO SPEND MY MONEY?</a></li> -->
    <li><a href="/">GAMES BY DESCRIPTION</a></li>
  </ul>

  <ul id="drpodown-menu-mobile" class="dropdown-content">
    <li><a href="{% url 'newgames:index' %}">NEW GAMES</a></li>
    <!-- <li><a href="/">HOW TO SPEND MY MONEY?</a></li> -->
    <li><a href="/">GAMES BY DESCRIPTION</a></li>
  </ul>

  <script type="text/javascript">
    $( document ).ready(function(){
        $(".button-collapse").sideNav();
    });
  </script>


  <nav>
    <a href="#" data-activates="nav-mobile" id="nav-button" class="button-collapse"><i id="menu_icon" class="material-icons" style="font-size: 36px">menu</i></a>
    <div class="nav-wrapper">

      <div class="container">
            
            <a href="/" class="brand-logo">
              <img id="steamrec_logo" src="{% static 'img/steamrec_logo2.png' %}" alt="STEAMREC" />
              <img id="steamrec_logo_medium" src="{% static 'img/steamrec_logo_medium.png' %}" alt="STEAMREC" />
              <img id="steamrec_logo_mini" src="{% static 'img/steamrec_logo_mini.png' %}" alt="STEAMREC" />
            </a>


            <ul id="nav-top" class="right hide-on-med-and-down nav-menu">
              <li><a class="dropdown-button" href="/" data-activates="drpodown-menu" data-beloworigin="true">RECOMMEND<i class="material-icons right">arrow_drop_down</i></a></li>
              
              <li><a href="/">ABOUT</a></li>

<!--               {% if steamid %}
              <li><a href="/">PROFILE</a></li>
              {% else %}
              {% endif %}

              {% if not steamid %}
              <li id="login"><a href="/login/" class="waves-effect waves-light btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="via Steam">LOGIN</a></li>
              {% else %}
              <li id="login"><a href="/logout/" class="waves-effect waves-light btn">LOGOUT</a></li>
              {% endif %} -->
            </ul>

            <ul id="nav-mobile" class="side-nav nav-menu">
              <li><a class="dropdown-button" href="/" data-activates="drpodown-menu-mobile" data-beloworigin="true">RECOMMEND<i class="material-icons right">arrow_drop_down</i></a></li>
              
              <li><a href="/">ABOUT</a></li>

            </ul>


      </div>


    </div>

  </nav>


{% endblock %}